version: '3'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    container_name: projeto1
    restart: always
    volumes:
      - postgres-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: projeto1

volumes:
  postgres-disk: 
